### ISSUE TITLE
BITRequestManager eventsFromData always returns nil

### ISSUE THREAD

**Issue by ndoe049** [adamcumiskey/BandsintownAPI#2]
- (NSArray *)eventsFromData:(NSData *)data
  {
  NSDictionary *jsonDictionary = [data objectFromJSONData];
  if (jsonDictionary && (id)jsonDictionary != [NSNull null]) {
  }
  return nil;
  }

**Comment by adamcumiskey** [comment]
Filled in this method definition. However the event search is still pretty weak at the moment though. It looks like it only successfully queries All events for an artist. The Location, Date Range, and Only_Recs options aren't returning any results at the moment.
